# this secret file should not be committed to repository
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
# base64 encoded, hardcoded as its solely for study purpose
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
